/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 8.6 and the Signal Processing Toolbox 7.1.
 * Generated on: 11-Oct-2017 16:49:27
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 58
 * Stable            : Yes
 * Linear Phase      : Yes (Type 2)
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2015b\extern\include\tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   single-precision filter coefficients.
 */
const int BL = 58;
const real32_T B[58] = {
  -0.006835767534,-0.0001287975028, 0.001011819462, 0.002859717235, 0.005234236829,
   0.007840729319,  0.01028612256,  0.01211740635,  0.01288195327,   0.0122014191,
   0.009848706424, 0.005815302487,0.0003548534878,-0.006007892545, -0.01250642445,
   -0.01819767803, -0.02205833979, -0.02310673892,  -0.0205419641, -0.01388948597,
  -0.003023079131,  0.01167452801,  0.02940613776,  0.04895731807,  0.06882610172,
    0.08737079054,   0.1029818207,   0.1142592356,   0.1201712489,   0.1201712489,
     0.1142592356,   0.1029818207,  0.08737079054,  0.06882610172,  0.04895731807,
    0.02940613776,  0.01167452801,-0.003023079131, -0.01388948597,  -0.0205419641,
   -0.02310673892, -0.02205833979, -0.01819767803, -0.01250642445,-0.006007892545,
  0.0003548534878, 0.005815302487, 0.009848706424,   0.0122014191,  0.01288195327,
    0.01211740635,  0.01028612256, 0.007840729319, 0.005234236829, 0.002859717235,
   0.001011819462,-0.0001287975028,-0.006835767534
};